### ISSUE TITLE
Undefined list components for plotting the effect of perturbations in inst/simulate_multivariate_normal_mixture_sensitivities.R

### ISSUE THREAD

**Issue by Mamie** [rgiordan/MVNMixtureLRVB#1]
Dear @rgiordan,

The following error occurred when we tried to run line 172-173 of inst/simulate_multivariate_normal_mixture_sensitivities.R

```
> x.col <- 1
> this.x.df <- filter(x.df, col == x.col)
Error: comparison (1) is possible only for atomic and list types
```

It looks like`x.df` does not have a component named `col`.

In addition, on line 178, 183, 188, 193, `mu_1_1`, `mu_1_2`, `mu_2_1`, `mu_2_2` (the values for the color option of the aesthetic mapping) doesn’t seem to be defined for `this.x.df`. And similarly for `lambda_1_1_1`, `lambda_1_2_2`, `lambda_2_1_1`, `lambda_2_2_2` on line 201, 206, 211, 216.

/cc @marivascruz

**Comment by rgiordan** [comment]
Thanks for noticing this!  I'm looking into it.  It looks like I deleted some necessary munging of the sensitivity results when I cleaned this up.

**Comment by rgiordan** [comment]
Ok, I've pushed a fix.  Please try it again.  As you've noticed, I believe nobody has really looked at this since I copied it over from my workbench repo, and I'm afraid there may be more gotchas waiting.  Please bear with me, and I'll do my best to be responsive when you find them.

**Comment by Mamie** [comment]
It's working now. Thanks!
